# Generated by Django 3.1.2 on 2020-10-19 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User id (UID)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User email')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='User registration date')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Last time user model has changed')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is user superuser')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='User nickname')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
