# Generated by Django 3.1.2 on 2020-10-20 11:52

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201020_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='User nickname'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['registration_date'], name='users_user_registr_aff0bd_brin'),
        ),
    ]
