# Generated by Django 3.1.2 on 2020-10-21 18:02

from django.db import migrations, models
import entropy.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201020_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[entropy.validators.Argon2HashValidator()], verbose_name='password'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('password__length', 75), ('password__startswith', 'argon2id')), name='argon2_hash_check'),
        ),
    ]
