# Generated by Django 3.1.2 on 2020-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201025_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is user superuser'),
        ),
    ]
