#  Django Rest Framework settings

default:

  REST_FRAMEWORK:

      TEST_REQUEST_DEFAULT_FORMAT: json

      DEFAULT_RENDERER_CLASSES':
          - drf_ujson.renderers.UJSONRenderer
          - rest_framework.renderers.BrowsableAPIRenderer

      DEFAULT_PARSER_CLASSES:
          - drf_ujson.parsers.UJSONParser
          - rest_framework.parsers.FormParser
          - rest_framework.parsers.MultiPartParser

development:
#  REST_FRAMEWORK:
#    DEFAULT_AUTHENTICATION_CLASSES:
#      - rest_framework_simplejwt.authentication.JWTAuthentication

production:

test:
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
      - rest_framework_simplejwt.authentication.JWTAuthentication