#  DJOSER settings

default:

    DJOSER:
        SERIALIZERS:
            user_create: users.serializers.CustomUserCreateSerializer
            current_user: users.serializers.CustomUserSerializer

development:

    DJOSER:
        PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND: True # default - False
        USERNAME_RESET_SHOW_EMAIL_NOT_FOUND: True # default - False

production:

  DJOSER:
      PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND: False # default - False
      USERNAME_RESET_SHOW_EMAIL_NOT_FOUND: False # default - False

test: