# Generated by Django 3.1.2 on 2020-10-31 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='language family')),
            ],
            options={
                'verbose_name': 'Language family',
                'verbose_name_plural': 'Language families',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=2, verbose_name='country code acc. ISO 639')),
                ('name', models.CharField(editable=False, max_length=23, verbose_name='language name')),
                ('family', models.ManyToManyField(related_name='_language_family_+', related_query_name='language', through='memorization.Family', to='memorization.Language', verbose_name='language family')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='first_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_language', to='memorization.language', verbose_name='first language'),
        ),
        migrations.AddField(
            model_name='family',
            name='second_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_language', to='memorization.language', verbose_name='second language'),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('first_language', 'second_language', 'name')},
        ),
    ]
