# Generated by Django 3.1.2 on 2020-10-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('code', 'name')},
        ),
    ]
