# Generated by Django 3.1.2 on 2020-11-02 09:26

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0006_auto_20201101_1058'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='family',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, first_language=django.db.models.expressions.F('second_language')), name='point_on_itself_check'),
        ),
    ]
