# Generated by Django 3.1.3 on 2020-11-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0008_auto_20201116_1944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='word',
            name='language',
        ),
    ]
