# Generated by Django 3.1.3 on 2020-11-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_extensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='translation',
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_word', to='memorization.word', verbose_name='first word')),
                ('to_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_word', to='memorization.word', verbose_name='second word')),
            ],
        ),
    ]
