# Generated by Django 3.1.2 on 2020-10-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0003_auto_20201031_1556'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='family',
            index_together={('first_language', 'second_language')},
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=30, verbose_name='one word')),
                ('definition', models.CharField(max_length=300, verbose_name='one word definition')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memorization.language', verbose_name='language of the word')),
                ('translation', models.ManyToManyField(related_name='_word_translation_+', to='memorization.Word', verbose_name='same words in another languages')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'unique_together': {('word', 'language')},
            },
        ),
    ]
