# Generated by Django 3.1.3 on 2020-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_auto_20201118_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.ManyToManyField(related_name='_word_translation_+', related_query_name='word', through='memorization.Connections', to='memorization.Word', verbose_name='same words in another languages'),
        ),
    ]
