# Generated by Django 3.1.2 on 2020-10-31 16:42

from django.db import migrations
from memorization.language_codes import codes_dict

#  Populates 'Language' models DB table with language codes and names.


def forwards_func(apps, schema_editor):
    """
    Populate 'Language' model with language codes and names
    """
    Language = apps.get_model('memorization', 'Language')
    language_instances = [
        Language(code=code, name=name) for code, name in codes_dict.items()
    ]
    Language.objects.bulk_create(language_instances)


def reverse_func(apps, schema_editor):
    """
    Truncate 'Language' model's DB table.
    """
    Language = apps.get_model('memorization', 'Language')
    Language.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0004_auto_20201031_1758'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
