# Generated by Django 3.1.3 on 2020-11-18 16:50

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('memorization', '0005_word_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connections',
            options={'verbose_name': 'Word connection', 'verbose_name_plural': 'Word connections'},
        ),
        migrations.AlterUniqueTogether(
            name='connections',
            unique_together={('to_word', 'from_word')},
        ),
        migrations.AddConstraint(
            model_name='connections',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, from_word=django.db.models.expressions.F('to_word')), name='word_ne_self_check'),
        ),
    ]
