# Generated by Django 3.1.3 on 2020-11-23 07:52

import django.db.models.expressions
from django.db import migrations, models

from memorization.models import NoteBook


class Migration(migrations.Migration):
    table_name = NoteBook._meta.db_table
    # Function checks whether learn_in_language is equal to word's language or not.
    # returns True when not equal and False in opposite scenario.
    # In check constraint learn_in_language != word's language is correct.
    function_sql = \
        """
        CREATE OR REPLACE FUNCTION is_different_language(word_id int , learn_in_language_id varchar)
                               RETURNS BOOLEAN AS
                                $$
                                   SELECT language_id != learn_in_language_id
                                   FROM memorization_word
                                   WHERE word_id = word_id
                                $$ 
                               LANGUAGE sql;
        """
    function_reverse_sql = \
        """
        DROP FUNCTION is_different_language(word_id int , learn_in_language_id varchar)
        """

    dependencies = [
        ('memorization', '0008_auto_20201122_2041'),
    ]

    operations = [
        migrations.RunSQL(
            sql=function_sql,
            reverse_sql=function_reverse_sql,
        ),
        migrations.AddConstraint(
            model_name='notebook',
            constraint=models.CheckConstraint(
                check=django.db.models.expressions.Func(django.db.models.expressions.F('word_id'),
                                                        django.db.models.expressions.F('learn_in_language_id'),
                                                        function='is_different_language',
                                                        output_field=models.BooleanField()),
                name='same_language_check'),
        ),
    ]
